/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#c6c6c8',
        surface: '#f8faf9',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'tertiary-fixed': '#ffdcbe',
        'surface-bright': '#f8faf9',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'outline-variant': '#bec8ce',
        'surface-tint': '#006783',
        'inverse-primary': '#7ad2f6',
        'tertiary-fixed-dim': '#ffb86f',
        'secondary-container': '#e0dfe1',
        'status-pending': '#0288D1',
        'on-secondary-fixed': '#1a1c1d',
        'surface-dark': '#1A1C1E',
        'surface-container': '#eceeed',
        'secondary-fixed': '#e3e2e4',
        'surface-container-low': '#f2f4f3',
        'primary-container': '#0c7e9f',
        'error-container': '#ffdad6',
        'status-warning': '#F57C00',
        'surface-container-high': '#e6e9e8',
        tertiary: '#874f01',
        'on-secondary-fixed-variant': '#464749',
        'on-primary-container': '#fbfdff',
        outline: '#6f797e',
        'surface-container-highest': '#e1e3e2',
        'on-background': '#191c1c',
        background: '#f8faf9',
        'on-primary-fixed': '#001f29',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#004d63',
        'on-tertiary-fixed': '#2c1600',
        'status-success': '#2E7D32',
        'tertiary-container': '#a4671e',
        'on-surface': '#191c1c',
        'surface-variant': '#e1e3e2',
        secondary: '#5d5e60',
        'on-secondary-container': '#626365',
        'status-critical': '#D32F2F',
        'on-surface-variant': '#3f484d',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#d8dad9',
        'inverse-on-surface': '#eff1f0',
        'on-tertiary-fixed-variant': '#693c00',
        'on-secondary': '#ffffff',
        'primary-fixed': '#bce9ff',
        'inverse-surface': '#2e3131',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#7ad2f6',
        primary: '#00647f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '32px',
        'margin-mobile': '16px',
        base: '8px',
        'max-width': '1440px',
        gutter: '16px',
      },
      fontFamily: {
        'body-lg': ['"IBM Plex Sans"', 'sans-serif'],
        'body-md': ['"IBM Plex Sans"', 'sans-serif'],
        'label-sm': ['"IBM Plex Sans"', 'sans-serif'],
        'label-md': ['"IBM Plex Sans"', 'sans-serif'],
        'headline-md': ['"IBM Plex Sans"', 'sans-serif'],
        'display-lg': ['"IBM Plex Sans"', 'sans-serif'],
        'headline-lg': ['"IBM Plex Sans"', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
