export const GRASERAS_SEED = [
    { codigo: 'TU23', temp: '100', calentador: '1' },
    { codigo: 'TU20', temp: '100', calentador: '7' },
    { codigo: 'TU17', temp: '100', calentador: '3' },
    { codigo: 'TU19', temp: '100', calentador: '' },
    { codigo: 'TU57', temp: '100', calentador: '' },
    { codigo: 'TU58', temp: '90', calentador: '' },
    { codigo: 'PL02', temp: '', calentador: '' },
    { codigo: 'PL03', temp: '', calentador: '' },
    { codigo: 'DT03', temp: '90', calentador: '' },
    { codigo: 'DT02', temp: '90', calentador: '' },
    { codigo: 'DT22', temp: '100', calentador: '' },
    { codigo: 'DT23', temp: '100', calentador: '4' },
    { codigo: 'DT14', temp: '100', calentador: '' },
    { codigo: 'DT01', temp: '90', calentador: '' },
    { codigo: 'DT21', temp: 'Fijo', calentador: '11' },
    { codigo: 'DT13', temp: '100', calentador: '' },
    { codigo: 'TU01', temp: '90', calentador: '5' },
    { codigo: 'TU02', temp: '90', calentador: '' },
    { codigo: 'TU16', temp: '90', calentador: '6' },
    { codigo: 'TU04', temp: '120', calentador: '10' },
    { codigo: 'TU54', temp: '100', calentador: '' },
    { codigo: 'TU39', temp: '70', calentador: '' },
    { codigo: 'TU40', temp: '70', calentador: '' },
    { codigo: 'TU43', temp: '100', calentador: '' },
    { codigo: 'TU26', temp: '70', calentador: '' },
    { codigo: 'TU27', temp: '70', calentador: '' },
    { codigo: 'TU25', temp: '100', calentador: '' },
    { codigo: 'TU32-33', temp: '', calentador: '' },
    { codigo: 'TU34-35', temp: '', calentador: '' },
    { codigo: 'TU48', temp: '120', calentador: '2' },
    { codigo: 'TU46', temp: '100', calentador: '' },
    { codigo: 'TU47', temp: '90', calentador: '' },
    { codigo: 'TU44', temp: '100', calentador: '' },
    { codigo: 'TU45', temp: '130', calentador: '' },
    { codigo: 'TU41', temp: '120', calentador: '12' },
    { codigo: 'TU42', temp: '120', calentador: '9/10' },
    { codigo: 'TU50', temp: '120', calentador: '' },
    { codigo: 'TU51', temp: '100', calentador: '12' },
    { codigo: 'DT12', temp: '90', calentador: '' },
    { codigo: 'DT20', temp: '100', calentador: '' },
    { codigo: 'DT15', temp: '100', calentador: '' },
    { codigo: 'PL04', temp: '150', calentador: '' },
    { codigo: 'SO01', temp: '100', calentador: '2' },
    { codigo: 'SO02', temp: '100', calentador: '' },
    { codigo: 'Lubricadora', temp: '', calentador: '' },
    { codigo: 'EX1', temp: '', calentador: '' },
    { codigo: 'EX2', temp: '', calentador: '' },
    { codigo: 'Encendido de Bomba de Agua', temp: '', calentador: '' },
    { codigo: 'Calentador Tolba EX02', temp: '', calentador: '' },
    { codigo: 'Llave de Vapor', temp: '', calentador: '' },
]